First commit
rtdip/core pull request #126
Opened 2023-03-30 09:21 UTC by vbayon

First Commit. Review for structure and integration witn main line.

2023-04-06 06:57 UTC, GBBBAS approved these changes

2023-04-06 08:03 UTC, GBBBAS commented
@vbayon 

For the folder structure, I would suggest:

**AMI Meters**
1. Create a file called `rtdip_sdk/data_models/meters/ami_meters.py`
2. Move the classes `MetaData`, `SeriesType`, `ModelType`, `UoMUsage`, `Usage`, `pjm_voltage_lvl` into `ami_meters.py`. That way it would be simpler to import them in the code such as `from rtdip_sdk.data_models.meters.ami_meters import MetaData` 
3. Move the `utils` folder into the new folder `rtdip_sdk/data_models/meters`

**Weather**

1. Move the `constants/weather_constants.py` file to `rtdip_sdk/data_models/weather` and call the file `constants.py`
 
**Tests**

1. Change the test folders to reflect the above changes

**Transformers**

1. The transformers folder - it would be good to understand the exact function of that code and whether it might be better positioned in the Pipelines section?

** Build Errors**

Can you review the build errors and fix what is being flagged?

2023-04-06 08:09 UTC, vbayon commented
@GBBBAS I will look into it!

2023-04-06 08:17 UTC, GBBBAS requested changes

2023-04-06 08:17 UTC, GBBBAS commented on src/sdk/python/rtdip_sdk/data_models/constants/weather_constants.py
Move this file to weather folder and rename to constants.py

2023-04-06 08:17 UTC, GBBBAS commented on src/sdk/python/rtdip_sdk/data_models/series/SeriesType.py
Please see comments [here](https://github.com/rtdip/core/pull/126#issuecomment-1498650663)

2023-04-06 08:17 UTC, GBBBAS commented on src/sdk/python/rtdip_sdk/data_models/utils/CreateUsageObject.py
Please see comments [here](https://github.com/rtdip/core/pull/126#issuecomment-1498650663)

2023-04-12 07:38 UTC, vbayon commented
@GBBBAS I have done a big refactoring. Please check. Thanks! /V

2023-04-12 11:03 UTC, cching95 approved these changes

2023-04-14 13:46 UTC, cching95 commented on src/sdk/python/rtdip_sdk/data_models/constants/weather_constants.py
constants file was removed

2023-04-14 15:27 UTC, cching95 approved these changes

2023-04-14 15:30 UTC, cching95 approved these changes

2023-04-14 15:41 UTC, merged